project:
  type: website
  output-dir: docs
  execute-dir: project
  resources:
    - assets/**

website:
  title: "Angel Yan"
  page-navigation: true
  back-to-top-navigation: true
  search: true

  navbar:
    background: light

    left:
      - text: "Home"
        href: more_about_me.qmd

      - text: "COMP/STAT112-01"
        menu:
          - text: "Portfolio"
            href: portfolio.qmd

          - text: "Personal Viz Journey"
            href: pvj/pvj-01.qmd

          - text: "TidyTuesday"
            href: tt/tt-README.qmd

          - text: "Pre-Class Learnings"
            href: pcl/pcl.qmd

          - text: "In-Class Activities"
            href: ica/ica-portfolio.qmd

          - text: "Extras"
            href: extra/extra-sample1.qmd

      - text: "Experience"
        href: experience.qmd

  sidebar:
    title: "Angel Yan"


format:
  html:
    theme:
      light: flatly
      dark: darkly

    css:
      - style/custom.css
      - style/style_Portfolio_index.css

    toc: true
    toc-depth: 3

    link-external-newwindow: true
    fontsize: 1em
    smooth-scroll: true

    code-overflow: scroll
    code-copy: true
    code-link: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#1482FA"
    code-tools: true
    code-fold: true

    page-layout: full
    number-sections: false
    toc-expand: true


execute:
  echo: true
  warning: false
  error: false
  cache: false


editor:
  mode: source

  markdown:
    wrap: sentence
